export const HEADER_INCREMENT = 'HEADER_INCREMENT';
export const HEADER_DECREMENT = 'HEADER_DECREMENT';

export const CREATE_CALENDER_ARRAY = 'CREATE_CALENDER_ARRAY';
export const GET_CLICK_DATE = 'GET_CLICK_DATE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
